### ISSUE TITLE
Would you mind to update the peerDeps to cover gulp v4

### ISSUE THREAD

**Issue by 3cp** [konclave/gulp-swc#2]
Hi, this plugin code looks working in gulp v4 just fine. Could you update the package.json peerDependencies to cover both gulp v3 and v4?

**Comment by konclave** [comment]
Have you tested it with gulp v4?

**Comment by 3cp** [comment]
Yes, it works.
I tried in an app project using gulp v4, replaced gulp-typescript with gulp-swc. Only got a problem with source map
```
 Error in plugin "gulp-swc"
Message:
    Source map to be applied is missing the "file" property
```
So I disabled source map, then everything just worked.

**Comment by konclave** [comment]
Released a new version with updated peer dependencies. 
Fixed the source map issue as well.
